# 基本配置
baseconfig:
  # 是否是https请求
  EncryptionRequest: false
  # 启动端口
  port: '7001'
  title: "TypeScript"
  #限流参数
  limitRequest:
    # 桶的流速，单位毫秒，桶内数量的流失速度
    rate: 1000
    # 桶的容量
    capacity: 5
# Redis
cache:
  host: localhost
  port: 6379
  #连接的库号
  db: 1
  # 一天的秒数
  ttl: 86400

# rabbitMQ
amqp:
  host: localhost
  port: 5672

